#!-- breakPoint - This refers to the 4 breakpoints DESKTOP, TABLET, MOBILE or MobileApp --!
#!-- deviceOS - This refers to the OS either IOS, ANDROID, Window, Mac --!
#------------------------------------------#
breakPoint=Desktop
deviceOS=Windows
appUrl = http://172.16.60.128:8081
appiumHost = 127.0.0.1
appPath= /Users/Automation/Apps/IOS/MyHealth
emulator=false
maximizeBrowser=yes

#Mobile Device App Config Details
#------------------------------------------#	
#Common Specific	
touchId=true	
deviceName=Samsung s6
# platformName - This refer to 2 breakpoints IOS or Android.
platformName=android
PlatformVersion=6.0.1
resetMode=full

#Android Specific Change the appPackage and appActivity of the app under test
deviceId = 031603e24c8d1a02
appPackage =
appActivity = 
			  

#Ios Specific
bundleId=com.test.myhealth
udid=cea83283a53bf849d7d56787d9fc5d930fdc6dc4818

#Wait Time
#------------------------------------------#
elementWaitInSeconds=20
sdk_location = /Users/Software/Android

autoexecutionstatus=true

zapi.baseurl=https://prod-api.zephyr4jiracloud.com/connect
jira.baseurl=https://tesr.atlassian.net
jira.authorization=c2FjaGluOlBob3RvbjIwMTcq
zapi.accesskey=NDJiNTMyNWUtOTJkNy0zZDVhLTg4NTQtOWFjZDdiOGU3YWI2IHNhY2hpbi5zb25rdXNhbGUgVVNFUl9ERUZBVUxUX05BTUU
zapi.secretkey=GJO6cmwrFaxVkVRPBb6ftNj-tX5OEM5qkpYEYO91A64
zapi.userName=test
project.key=CA
release.version=TestingVersion
testcycle.name=SmokeTest